name: adb_master
description: ADB Master V6.1 Clone.
publish_to: 'none'
version: 6.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Thư viện chọn file cho tab FLASH
  file_picker: ^6.1.1 
  # Thư viện icon đẹp
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


