name: adb_master
description: ADB Master V6.2 Non-Root.
publish_to: 'none'
version: 6.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  cupertino_icons: ^1.0.2
  # Thêm cái này để lấy thông tin bộ nhớ máy
  disk_space: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


