name: adb_master
description: ADB Master Clone V6.
publish_to: 'none'
version: 6.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Thư viện chọn file cho tab Flash
  file_picker: ^6.1.1
  # Bộ icon đẹp
  cupertino_icons: ^1.0.2
  # Hiệu ứng phần trăm vòng tròn
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


